name = "teron-feedback-api-dev"
main = "src/index.ts"
compatibility_date = "2024-01-29"
workers_dev = true

[assets]
directory = "public"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"
ALLOWED_ORIGINS = "*"
ALLOWED_REPOSITORIES = "sello-rex/teron-feedback"
GITHUB_APP_NAME = "teron-feedback-app"
MAX_SCREENSHOT_SIZE_MB = "5"

[durable_objects]
bindings = [{ name = "FEEDBACK_COUNTER", class_name = "FeedbackCounter" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FeedbackCounter"]

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c6abc9d7baf640dca9437d69ba4b7503"
preview_id = "59bc04cd27544de9870b0e87b43753fe"

[env.preview]
name = "teron-feedback-api-preview"
workers_dev = true
routes = []

[env.preview.assets]
directory = "public"
binding = "ASSETS"

[env.preview.vars]
ENVIRONMENT = "preview"
ALLOWED_ORIGINS = "https://teron.co.za"
ALLOWED_REPOSITORIES = "sello-rex/teron-feedback"
GITHUB_APP_NAME = "teron-feedback-app"
MAX_SCREENSHOT_SIZE_MB = "5"

[env.preview.durable_objects]
bindings = [{ name = "FEEDBACK_COUNTER", class_name = "FeedbackCounter" }]

[[env.preview.kv_namespaces]]
binding = "RATE_LIMIT"
id = "59bc04cd27544de9870b0e87b43753fe"

[env.production]
name = "teron-feedback-api"
workers_dev = true
routes = []
preview_urls = false

[env.production.assets]
directory = "public"
binding = "ASSETS"

[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://teron.co.za"
ALLOWED_REPOSITORIES = "sello-rex/teron-feedback"
GITHUB_APP_NAME = "teron-feedback-app"
MAX_SCREENSHOT_SIZE_MB = "5"

[env.production.durable_objects]
bindings = [{ name = "FEEDBACK_COUNTER", class_name = "FeedbackCounter" }]

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "c6abc9d7baf640dca9437d69ba4b7503"

[env.preview.observability]
enabled = true

[env.preview.observability.logs]
enabled = true

[env.preview.observability.traces]
enabled = true

[env.production.observability]
enabled = true

[env.production.observability.logs]
enabled = true

[env.production.observability.traces]
enabled = true
